name: booksearch
services:
  postgres:
    image: postgres:16-alpine
    container_name: bk-db
    ports:
      - 5432:${POSTGRES_PORT}
    volumes:
      - g10-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - g10-net
volumes:
  g10-data:
networks:
  g10-net:
